name: Regression Model CI

on:
  push:
    branches:
      - reg_branch 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Set up Python
      uses: actions/setup-python@v5 
      with:
        python-version: '3.9' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Install packages from requirements.txt

    - name: Run Regression Models
      run: |
        python regression.py # Execute your regression script
        